[package]
name = "genius-rs"
version = "0.1.1"
authors = ["Pedro Mendes <pedromendescraft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
scraper = "0.12.0"


[dev-dependencies]
tokio = {version = "1.5.0", features = ["full"]}
dotenv = "0.15.0"