[package]
name = "genius-rs"
version = "0.1.0"
authors = ["Pedro Mendes <pedromendescraft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.2"
tokio = {version = "1.5.0", features = ["full"]}
dotenv = "0.15.0"